const assert=require('node:assert/strict');const {chromium:pw}=require('playwright');const path=require('node:path');
(async()=>{
process.env.VITE_SUPABASE_URL='https://test.supabase.co';process.env.VITE_SUPABASE_ANON_KEY='test-key';
const {createServer}=await import('vite');
const vite=await createServer({root:path.resolve(__dirname,'..'),server:{host:'127.0.0.1',port:5173}});await vite.listen();
const browser=await pw.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
const user='00000000-0000-0000-0000-000000000001',other='00000000-0000-0000-0000-000000000002',ticket='00000000-0000-0000-0000-000000000003';
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date());const plus=n=>{const d=new Date(today+'T12:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
const payload={sub:user,exp:Math.floor(Date.now()/1000)+86400,iat:Math.floor(Date.now()/1000)};const token=[{alg:'HS256',typ:'JWT'},payload].map(o=>Buffer.from(JSON.stringify(o)).toString('base64url')).join('.')+'.test';
await page.addInitScript(({token,user})=>localStorage.setItem('sb-test-auth-token',JSON.stringify({access_token:token,refresh_token:'mock',expires_at:Math.floor(Date.now()/1000)+86400,expires_in:86400,token_type:'bearer',user:{id:user,email:'felipe@ctp.test',aud:'authenticated',role:'authenticated',user_metadata:{name:'Felipe'}}})),{token,user});
const users=[{id:user,name:'Felipe',role:'felipe',can_access_feed:true},{id:other,name:'Manu',role:'executor',can_access_feed:true}];
let events=[{id:'e1',title:'Aula de teste',kind:'aula',day:plus(1),starts_at:'08:00',ends_at:'12:00',participant_ids:[user,other],preparation_deadline:today,status:'confirmed',location:'Maker',series_id:null}];
let items=[{id:'i1',title:'Modelar suporte',ticket_id:ticket,event_id:null,ticket_task_id:1,assignee_id:user,remaining_minutes:120,due_date:null,status:'pending'}];
let blocks=[{id:'b1',work_item_id:'i1',user_id:user,day:plus(-1),period:'tarde',minutes:60,status:'planned'}];const availability=users.flatMap(u=>[1,2,3,4,5].flatMap(weekday=>['manha','tarde'].map(period=>({user_id:u.id,weekday,period,starts_at:period==='manha'?'08:00':'13:00',ends_at:period==='manha'?'12:00':'17:00'}))));
const tickets=[{id:ticket,titulo:'Rover de teste',tipo:'interna',origem:'interno',categoria:'engenharia',prioridade:'media',status:'em_producao',responsavel_id:user,data_criacao:today,data_entrega:plus(4),responsavel:{id:user,name:'Felipe'}}];const calls=[];
await page.route('https://test.supabase.co/**',async route=>{const req=route.request(),url=new URL(req.url()),path=url.pathname.split('/').at(-1),body=req.postDataJSON();let result=[];if(req.method()==='OPTIONS'){await route.fulfill({status:200,headers:{'access-control-allow-origin':'*'}});return}
 if(url.pathname.includes('/auth/'))result={user:{id:user,email:'felipe@ctp.test'}};
 else if(url.pathname.includes('/rpc/')){calls.push({path,body});if(path==='maker_continue_block'){const b=blocks.find(b=>b.id===body.block_id);items[0].remaining_minutes=body.remaining;b.status=body.new_day?'superseded':'needs_reschedule';if(body.new_day)blocks.push({...b,id:'b2',status:'planned',day:body.new_day,period:body.new_period,minutes:body.new_minutes});result=null}else if(path==='maker_complete_item'){items[0].status='completed';blocks.forEach(b=>b.status=b.id===body.block_id?'done':'cancelled');result=null}else if(path==='maker_create_event'){events.push({...body.payload,id:'e2',status:'confirmed',series_id:null});result='e2'}}
 else if(path==='app_users')result=url.searchParams.has('id')?users[0]:users;
 else if(path==='tickets')result=tickets;
 else if(path==='ticket_tasks')result=[{id:1,ticket_id:ticket,titulo:'Modelar suporte',responsavel_id:user,status:items[0].status==='completed'?'concluido':'pendente'}];
 else if(path==='maker_events')result=events;else if(path==='maker_work_items')result=items;else if(path==='maker_blocks')result=blocks;else if(path==='maker_availability')result=availability;
 await route.fulfill({status:200,contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:JSON.stringify(result)});
});
await page.goto('http://127.0.0.1:5173/planejamento');await page.getByRole('heading',{name:'Planejamento de equipe',exact:true}).waitFor();await page.getByRole('button',{name:'Continuar depois',exact:true}).first().waitFor();
assert(await page.getByText('1 bloco precisa de remanejamento').isVisible());await page.screenshot({path:'/tmp/ctp-planning-desktop.png',fullPage:true});
await page.getByRole('button',{name:'Continuar depois',exact:true}).first().click();await page.getByRole('heading',{name:'Quanto falta e quando vai continuar?'}).waitFor();await page.getByRole('button',{name:'Decidir depois · manter alerta'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});assert(calls.some(c=>c.path==='maker_continue_block'&&c.body.new_day===null));
await page.getByRole('button',{name:'Continuar depois',exact:true}).first().click();const select=page.getByRole('dialog').locator('select');const value=await select.locator('option:not([disabled])').first().getAttribute('value');await select.selectOption(value);await page.getByRole('button',{name:'Remanejar para este período'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});assert(calls.some(c=>c.path==='maker_continue_block'&&c.body.new_day));
await page.getByRole('button',{name:'Concluir etapa'}).first().click();await page.getByText('✓ Etapa concluída').first().waitFor();assert.equal(tickets[0].status,'em_producao');
await page.goto('http://127.0.0.1:5173/eventos');await page.getByRole('button',{name:'Novo evento',exact:true}).click();const form=page.getByRole('dialog');await form.locator('[name=title]').fill('Workshop novo');await form.locator('[name=day]').fill(plus(3));await form.locator('[name=start]').fill('14:00');await form.locator('[name=end]').fill('16:00');await form.locator('[name=participants]').first().check();await form.locator('[name=preparation]').fill('Testar atividade\nSeparar materiais');await form.getByRole('button',{name:'Cadastrar evento'}).click();await form.waitFor({state:'hidden'});assert(calls.some(c=>c.path==='maker_create_event'&&c.body.preparations.length===2));await page.getByRole('button',{name:'Semana',exact:true}).click();await page.screenshot({path:'/tmp/ctp-events-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/ctp-events-mobile.png',fullPage:true});assert.equal(errors.length,0,errors.join('\n'));
await page.goto('http://127.0.0.1:5173/relatorios');await page.getByRole('navigation',{name:'Visões de relatórios'}).waitFor();assert(await page.getByRole('navigation',{name:'Visões de relatórios'}).getByRole('link').count()===3);
console.log('OK: autenticação simulada, alerta vencido, decidir depois, remanejar, concluir sem mudar demanda, cadastro direto e relatórios; desktop e celular.');await browser.close();await vite.close();
})().catch(e=>{console.error(e);process.exit(1)});
